openapi: 3.0.1
info:
  title: DS_OPENSEARCH_API
  description: >-
    This is the EUMETSAT Data Store (EDS) OPENSEARCH API.

    For more information on the OpenSearch specification, see
    https://github.com/dewitt/opensearch
  termsOfService: https://www.eumetsat.int/terms/
  license:
    name: 'License: not yet defined. For the time being: confidential and private'
    url: https://www.eumetsat.int
  version: 0.4.0
servers:
  - url: https://api.eumetsat.int/data/search-products/0.4.0
  - url: http://api.eumetsat.int/data/search-products/0.4.0
security:
  - default: []
tags:
  - name: Search
    description: Search EUMETSAT Online EO Data
    externalDocs:
      description: Find out more
      url: https://www.eumetsat.int
paths:
  /os:
    get:
      tags:
        - Search
      summary: Search products
      description: Search products
      operationId: searchProducts
      parameters:
        - name: format
          in: query
          description: 'Format of response encoding: xml or json'
          required: false
          style: form
          explode: true
          schema:
            type: string
            enum:
              - json
              - xml
        - name: pi
          in: query
          description: 'eo:parentIdentifier: the collection identifier'
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: c
          in: query
          description: 'Count: Number of records to return'
          required: false
          style: form
          explode: true
          schema:
            maximum: 1000
            minimum: 0
            type: integer
        - name: si
          in: query
          description: 'StartIndex: start index of records to return'
          required: false
          style: form
          explode: true
          schema:
            minimum: 0
            type: integer
        - name: pw
          in: query
          description: 'StartPage: startPage of records to return.'
          required: false
          style: form
          explode: true
          schema:
            minimum: 0
            type: integer
        - name: dtstart
          in: query
          description: >-
            time:start: Temporal Start Date.
            minInclusive=2015-07-17T00:04:18.479Z,
            maxInclusive=2017-08-15T12:10:00Z
          required: false
          style: form
          explode: true
          schema:
            type: string
            format: date
        - name: dtend
          in: query
          description: >-
            time:end: Temporal End Date. minInclusive=2015-07-17T00:04:18.479Z
            maxInclusive=2017-08-15T12:20:00Z
          required: false
          style: form
          explode: true
          schema:
            type: string
            format: date
        - name: bbox
          in: query
          description: >-
            geo:box: Inventory which has a spatial extent overlapping this
            bounding box. The box is defined by - west, south, east, north -
            coordinates of longitude, latitude, in a EPSG:4326 decimal degrees
            (e.g. &bbox=2.0,10.0,10.0,52.0& )
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: geo
          in: query
          description: >-
            geo:geometry: a custom geomtery in Well Known Text format, in a
            EPSG:4326 decimal degrees (e.g. &geo=POLYGON((1 1,5 1,5 5,1 5,1
            1),(2 2,2 3,3 3,3 2,2 2))& )
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: sat
          in: query
          description: 'eo:platformShortName: Misssion / Satellite'
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: zone
          in: query
          description: 'eum:tileZone: Equi7grid main continental zone'
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: t6
          in: query
          description: 'eum:tileZone: Equi7grid 600km tile'
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: sort
          in: query
          description: >-
            sru:sort: result sorting, ingestion time and sesning time are
            supported
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: id
          in: query
          description: geo:uid
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: cycle
          in: query
          description: Cycle number
          required: false
          style: form
          explode: true
          schema:
            type: integer
        - name: orbit
          in: query
          description: Orbit number
          required: false
          style: form
          explode: true
          schema:
            type: integer
        - name: relorbit
          in: query
          description: Relative orbit number
          required: false
          style: form
          explode: true
          schema:
            type: integer
        - name: fire
          in: query
          description: Fire detected
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: timeliness
          in: query
          description: Timeliness
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: title
          in: query
          description: Product name
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: type
          in: query
          description: Product type
          required: false
          style: form
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: >-
            successful operation. The response is a representation of the
            search.
        '400':
          description: The client request has errors.
        '404':
          description: The requested resource was not found.
        '405':
          description: >-
            The HTTP method specified in the request is not allowed for this
            resource.
        '500':
          description: >-
            The REST API encountered an internal error that was not foreseen,
            e.g. because a backend service is down. Error details will be
            contained in the log files and not be returned to the client.
      security:
        - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
components:
  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid
      headers:
        WWW_Authenticate:
          style: simple
          explode: false
          schema:
            type: string
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://api.eumetsat.int/authorize
          scopes: {}
