openapi: 3.0.1
info:
  title: EDL Ingestion API
  description: >-
    This document describes the REST interface of the EUMETSAT Data Lake (EDL)
    Ingestion Service. EDL Ingestion service can be used by authorised Data
    Producers requesting the ingestion of a SIP Package located in a bucket
    accessible by the EDL.
  termsOfService: https://www.eumetsat.int/terms
  contact:
    name: EUMETSAT
    url: https://www.eumetsat.int
    email: edl@eumetsat.int
  license:
    name: 'License: not yet defined. For the time being: confidential and private'
  version: 1.1.0
servers:
  - url: https://api.edl.ope.dac.eumetsat.int/ingest/1.1.0
  - url: http://api.edl.ope.dac.eumetsat.int/ingest/1.1.0
security:
  - default: []
tags:
  - name: Ingestion
paths:
  /sip:
    post:
      tags:
        - Ingestion
      summary: Ingest a product packaged as a Submission Information Package (SIP)
      operationId: sipIngestionUsingPOST
      requestBody:
        description: body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EdlIngest'
        required: true
      responses:
        '202':
          description: ACCEPTED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EdlSuccessResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EdlFailureResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EdlFailureResponse'
        '404':
          description: SIP file not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EdlFailureResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EdlFailureResponse'
      security:
        - default: []
      x-codegen-request-body-name: body
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
components:
  schemas:
    EdlIngest:
      required:
        - sipUri
      type: object
      properties:
        sipUri:
          type: string
          description: URI of the SIP product in Virtual Hosted Style Request format
          format: uri
          example: >-
            https://<bucket>.s3.<region>.<host>/collection-1/MSG-1.5-RSS-HRIT_201710200905_201710200910.zip
        md5:
          type: string
          description: MD5 checksum of the SIP file referenced with the parameter sipUri
          example: 98ff10b54bf6d05b377a3f1a057c1c11
    EdlSuccessResponse:
      type: object
      properties:
        productUuid:
          type: string
          description: Unique ingestion identifier, if product was accepted
          format: uuid
    EdlFailureResponse:
      type: object
      properties:
        message:
          type: string
          description: Error message, if something went wrong
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://api.edl.ope.dac.eumetsat.int/authorize
          scopes: {}
